import { expect } from 'chai';
import proxyquire from 'proxyquire';
const Mock: any = { ... };

describe('UsersRepository', () => {
  let usersRepository: any;

  beforeEach(() => {
    usersRepository = new (proxyquire('../../src/repositories/users.repository', {
      'common/Users': Mock,
    })).UsersRepository();
  });

  describe('createUsers', () => {
    it('should call Users.insertMany and return void', async () => {
      const param: any[] = [{ name: 'John' }, { name: 'Jane' }];
      const UsersInsertManySpy: any = Mock.Users.insertMany;
      UsersInsertManySpy.mockResolvedValue({});

      await usersRepository.createUsers(param);

      expect(UsersInsertManySpy).to.have.been.calledWith(param);
    });
  });

  describe('deleteUser', () => {
    it('should call Users.findByIdAndDelete and return UsersModel | null', async () => {
      const id: string = '1234567890';
      const UsersFindByIdAndDeleteSpy: any = Mock.Users.findByIdAndDelete;
      UsersFindByIdAndDeleteSpy.mockResolvedValue({} as any);

      const result = await usersRepository.deleteUser(id);

      expect(UsersFindByIdAndDeleteSpy).to.have.been.calledWith({ _id: id });
      expect(result).to.be.null;
    });
  });

  describe('searchUsers', () => {
    it('should call Users.countDocuments, Users.find and return { count: number; rows: UsersModel[] }', async () => {
      const params: any = { name: 'John', email: 'john@example.com', status: 'active', role: 'admin' };
      const UsersCountDocumentsSpy: any = Mock.Users.countDocuments;
      const UsersFindSpy: any = Mock.Users.find;
      UsersCountDocumentsSpy.mockResolvedValue(10);
      UsersFindSpy.mockResolvedValue([{ name: 'John', email: 'john@example.com' } as any]);

      const result = await usersRepository.searchUsers(params);

      expect(UsersCountDocumentsSpy).to.have.been.calledWith({ userName: { $regex: 'john', $options: 'i' }, email: { $regex: 'john@example.com', $options: 'i' }, status: 'active', role: 'admin' });
      expect(UsersFindSpy).to.have.been.calledWith({ userName: { $regex: 'john', $options: 'i' }, email: { $regex: 'john@example.com', $options: 'i' }, status: 'active', role: 'admin' })
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().and.calledWithExactly()
        .and.calledWithExactly().