import {
  LayoutDashboard,
  Book,
  ChartColumnStacked,
  Users,
  BookA,
} from "lucide-react";

export const MENU_ITEMS = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    path: "/dashboard",
    showInPage: true,
    roles: ["admin", "librarian", "member"],
  },
  {
    id: "profile",
    label: "Profile",
    icon: LayoutDashboard,
    path: "/about-me",
    showInPage: false,
    roles: ["admin", "librarian", "member"],
  },
  {
    id: "book",
    label: "Book",
    icon: Book,
    path: "/books",
    showInPage: true,
    roles: ["admin", "librarian", "member"],
  },
  {
    id: "category",
    label: "Category",
    icon: ChartColumnStacked,
    path: "/categories",
    showInPage: true,
    roles: ["admin", "librarian"],
  },
  {
    id: "author",
    label: "Author",
    icon: BookA,
    path: "/author",
    showInPage: true,
    roles: ["admin", "librarian"],
  },
  {
    id: "users",
    label: "Users",
    icon: Users,
    path: "/users",
    showInPage: true,
    roles: ["admin", "librarian"],
  },
  {
    id: "role",
    label: "Role",
    icon: Users,
    path: "/role",
    showInPage: true,
    roles: ["admin"],
  },
];
