export enum NotificationType {
  BOOK_DUE = "BOOK_DUE",
  BOOK_OVERDUE = "BOOK_OVERDUE",
  BOOK_RESERVED = "BOOK_RESERVED",
  BOOK_RETURNED = "BOOK_RETURNED",
  NEW_ARRIVAL = "NEW_ARRIVAL",
  MEMBERSHIP_EXPIRY = "MEMBERSHIP_EXPIRY",
  FINE_IMPOSED = "FINE_IMPOSED",
}

export enum RolePermission {
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_BOOKS = "MANAGE_BOOKS",
  MANAGE_ROLES = "MANAGE_ROLES",
  VIEW_REPORTS = "VIEW_REPORTS",
  ISSUE_BOOKS = "ISSUE_BOOKS",
  RETURN_BOOKS = "RETURN_BOOKS",
}

export enum BorrowRecordsEnum {
  ISSUED = "ISSUED",
  RETURNED = "RETURNED",
  LOST = "LOST",
  OVERDUE = "OVERDUE",
}

export enum BookStatusEnum {
  AVAILABLE = "AVAILABLE",
  CHECKED_OUT = "CHECKED_OUT",
  RESERVED = "RESERVED",
  LOST = "LOST",
}

export enum AuditLogsActionEnum {
  CREATE_BOOK = "CREATE_BOOK",
  UPDATE_MEMBER = "UPDATE_MEMBER",
  DELETE_RECORD = "DELETE_RECORD",
  ISSUE_BOOK = "ISSUE_BOOK",
  RETURN_BOOK = "RETURN_BOOK",
}
