export const messages = {
  internalServerError: "Internal server error",
  badRequest: "Bad request",
  unauthorized: "Unauthorized access",
  forbidden: "Forbidden access",
  AuthorizationsMessages: {
    LoginSuccess: "Login successful",
    InvalidCredentials: "Invalid username or password",
    RefreshToken: "Refresh token successful",
    LogoutSuccess: "Logout successful",
    SignupSuccess: "Signup successful",
    PasswordUpdate: "Password update successfully.",
  },
  RoleMessages: {
    Create: "Role Created successfully.",
    Update: "Role Updated successfully.",
    Search: "Roles fetched successfully.",
    Get: "Role fetched successfully.",
    Delete: "Role deleted successfully.",
    NotFound: "Role not found.",
    RoleIsUnique: "Role already exists.",
  },
  UsersMessages: {
    UserNotFound: "User not found.",
    UserIsUnique: "User already exists",
    UsersCreated: "Users Created successfully.",
    UsersFetched: "Users fetched successfully.",
    Updated: "User updated successfully.",
    Deleted: "User deleted successfully.",
    UserIsInactive: "User is not active.",
    create: "User created successfully.",
  },
  CategoriesMessages: {
    CategoryNotFound: "Category not found.",
    CategoryIsUnique: "Category already exists",
    Created: "Category created successfully.",
    Fetched: "Categories fetched successfully.",
    Updated: "Category updated successfully.",
    Deleted: "Category deleted successfully.",
  },
};
